### ISSUE TITLE
File not found!

### ISSUE THREAD

**Issue by brunotrox** [segment-integrations/analytics-ios-integration-firebase#12]
Hi,

I've been trying to integrate Firebase through Segment using the iOS SDK: `Segment-Firebase`.

After installing the pod `Segment-Firebase` and trying to compile the project I get the following error:

**`FirebaseAnalytics/FIrebaseAnalytics.h` file not found**

It looks like the error has been generated at SEGFirebaseIntegration.m. I am also not able to import `import Segment_Firebase` to my classes. 

**Note:** The project has been developed in swift.

Best,

Bruno Agatte

**Comment by ladanazita** [comment]
@brunotrox Do you have `use_frameworks!` included in your podfile? This may be an issue with Firebase not being served as a dynamic library, so having this included will cause the issue you see. 

If you can remove `use_frameworks!` from your podfile, this issue should be resolved. However, if you can't remove that you may need to manually include the integration files in your project. So instead of importing the integration from our library, then you would import the integration from your local copy.

This eliminates the transitive dependency (from App -> Segment-Firebase -> Firebase to App -> Firebase).
