### ISSUE TITLE
Segement-Firebase fails to compile 

### ISSUE THREAD

**Issue by EfraimB** [segment-integrations/analytics-ios-integration-firebase#25]
The import of 'FirebaseAnalytics/FirebaseAnalytics.h' fails in file included from ../Pods/Segment-Firebase/Segment-Firebase/Classes/SEGFirebaseIntegration.m:3: with 'FirebaseAnalytics/FirebaseAnalytics.h' file not found ". Xcode 9.3 and Swift 4.1

**Comment by ladanazita** [comment]
Hi @EfraimB , could you provide your podfile here? 

If you are including `use_frameworks!` you may need to use the subspec `staticLibWorkaround` as described [here](https://github.com/segment-integrations/analytics-ios-integration-firebase/pull/23).

**Comment by benevbright** [comment]
Hi, @ladanazita 
So, using `Segment-Firebase/StaticLibWorkaround` is enough?
Looks like `Segment-Firebase/StaticLibWorkaround` is outdated from latest. 
And how come this is not in the README? 
Could you explain a bit more how we deal with now? I'm bit confused because your PR https://github.com/segment-integrations/analytics-ios-integration-firebase/pull/23 is merged.
