### ISSUE TITLE
Random crash while using Segmennt-Firebase

### ISSUE THREAD

**Issue by vaibhav-nickelfox** [segment-integrations/analytics-ios-integration-firebase#26]
After successfully adding 'Segment-Firebase/StaticLibWorkaround' via pods, when running app, getting a crash.
<img width="1012" alt="screen shot 2018-05-11 at 6 38 31 pm" src="https://user-images.githubusercontent.com/23524831/40063206-704de752-587a-11e8-90be-7cb244f78718.png">

**Comment by radiofreejohn** [comment]
@vaibhav-nickelfox I’ve seen a similar crash with firebase and a different library that also swizzles viewDidAppear (Heap - where I work), are you also using Firebase/Performance?

If so does the crash happen when you uninstall that pod?

Are you initializing Segment before or after Firebase?

**Comment by radiofreejohn** [comment]
@vaibhav-nickelfox interesting – I only saw this with the `Performance` pod – are you on the latest version of cocoapods and using the latest pods?

For what it's worth, on the performance pod, using the previous major version fixed the crash. I reached out to Firebase and they were not helpful – my best guess is that they are doing some aggressive method swizzling and in some situations, the swizzled methods don't play well with other libraries that also swizzle.

The only workaround I could come up with was to actually build our library to attempt to detect Firebase's swizzling and use a saved function pointer for the network connection. Since yours isn't related to `Performance` there's probably something else going on. The only thing I can think of that might give you more information is if you got a full backtrace from this crash to get a better idea of which part of Firebase is misbehaving.

Anyhow, sorry about this – I think as far as Firebase goes, it's a black hole, and the workaround I have is really brittle and I wouldn't recommend it :(

**Comment by vaibhav-nickelfox** [comment]
@radiofreejohn In my project, there were two targets one for Model and the other one for the project. Segment and Firebase were in Model. The workaround I tried was to remove Model and put Segment, Firebase and other pods in single target. So far I've not faced any related crash.

**Comment by alanjcharles** [comment]
Closing as there hasn't been any activity in a few years. Please reopen if still relevant
