### ISSUE TITLE
Upgrade Firebase SDK version to 8

### ISSUE THREAD

**Issue by raybotha** [segment-integrations/analytics-ios-integration-firebase#72]
A new major version of the Firebase iOS SDK is available, so conflicts are starting to show up between this package and others that depend on the newer version.

https://firebase.google.com/support/release-notes/ios

**Comment by twelve17** [comment]
Indeed:

```
CocoaPods could not find compatible versions for pod "FirebaseAnalytics":
  In Podfile:
    RNFBAnalytics (from `../node_modules/@react-native-firebase/analytics`) was resolved to 12.0.0, which depends on
      Firebase/Analytics (= 8.0.0) was resolved to 8.0.0, which depends on
        Firebase/Core (= 8.0.0) was resolved to 8.0.0, which depends on
          FirebaseAnalytics (~> 8.0.0)

    Segment-Firebase was resolved to 2.7.0, which depends on
      FirebaseAnalytics (~> 6.1)
```

**Comment by shamilovtim** [comment]
@bsneed any an ETA on this? it has been months and is starting to become urgent.

**Comment by bsneed** [comment]
@shamilovtim I searched high and low for your ticket and couldn't find it.  The only one I could find from you that was semi-related referenced upgrading to Firebase 7.4 and was filed middle of Jan and completed beginning of March.  I went ahead and made a ticket internally.  In the future please follow up on the support tickets rather than numerous posts and dupes on GitHub.

**Comment by shamilovtim** [comment]
We've had product reach out on two separate occasions @bsneed. I have no idea what in particular they did, if anything. But they were promised a response.

**Comment by bsneed** [comment]
@shamilovtim I'm not sure they actually got in touch on that topic unfortunately.  Regardless of where the ball got dropped, I did get it prioritized and should be done later this week or beginning of next week.
